{
 "title": "Env log",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temp Stan",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT value FROM temperature WHERE source_id=3 and $__timeFilter(time ) order by id DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Humidity stan",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "humidity",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT value FROM humidity WHERE source_id=4 and $__timeFilter(time ) order by id DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Temp ZG",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT value FROM temperature WHERE source_id=5 and $__timeFilter(time ) order by id DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Humidity ZG",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "format": "humidity",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT value FROM humidity WHERE source_id=6 and $__timeFilter(time ) order by id DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "PM10 dub µg/m3",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT value \nFROM \npm10 \nWHERE source_id=1 and $__timeFilter(time ) order by id DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Stan reported",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT time as t FROM temperature WHERE source_id=3 and $__timeFilter(time ) order by id DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "ZG OWM reported",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 0 },
   "format": "d",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT time as t FROM temperature WHERE source_id=5 and $__timeFilter(time ) order by id DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "air quality",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "conμgm3" }
   ],
   "targets": [
    {
     "rawSql": "select value, 'ZG-dub-pm10' as metric, \nUNIX_TIMESTAMP(time) as time_sec \nfrom pm10\nwhere source_id='1' and $__timeFilter(time)\norder by time asc "
    },
    {
     "rawSql": "select value, 'klaka1pm25' as metric, \nUNIX_TIMESTAMP(time) as time_sec \nfrom pm25\nwhere source_id='17' and $__timeFilter(time)\norder by time asc "
    }
   ]
  },
  {
   "title": "temperatura",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "select value, 'stan' as metric, \nUNIX_TIMESTAMP(time) as time_sec \nfrom temperature\nwhere source_id='3' and $__timeFilter(time)\norder by time asc "
    },
    {
     "rawSql": "select value, 'zgb' as metric, \nUNIX_TIMESTAMP(time) as time_sec \nfrom temperature\nwhere source_id='5' and $__timeFilter(time)\norder by time asc "
    },
    {
     "rawSql": "select value, 'stan2' as metric, \nUNIX_TIMESTAMP(time) as time_sec \nfrom temperature\nwhere source_id='11' and $__timeFilter(time)\norder by time asc "
    }
   ]
  },
  {
   "title": "humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "rawSql": "select value, 'stan' as metric, \nUNIX_TIMESTAMP(time) as time_sec \nfrom humidity\nwhere source_id='4' and $__timeFilter(time)\norder by time asc "
    },
    {
     "rawSql": "select value, 'zgb' as metric, \nUNIX_TIMESTAMP(time) as time_sec \nfrom humidity\nwhere source_id='6' and $__timeFilter(time)\norder by time asc "
    },
    {
     "rawSql": "select value, 'stan2' as metric, \nUNIX_TIMESTAMP(time) as time_sec \nfrom humidity\nwhere source_id='12' and $__timeFilter(time)\norder by time asc \n"
    }
   ]
  },
  {
   "title": "PM10 µg/m3",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "rawSql": "select value, 'ZG-dub' as metric, \nUNIX_TIMESTAMP(time) as time_sec \nfrom pm10\nwhere source_id='1' and $__timeFilter(time)\norder by time asc "
    }
   ]
  },
  {
   "title": "temperatura",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "select value, 'stan' as metric, \nUNIX_TIMESTAMP(time) as time_sec \nfrom temperature\nwhere source_id='3' and $__timeFilter(time)\norder by time asc "
    },
    {
     "rawSql": "select value, 'zgb' as metric, \nUNIX_TIMESTAMP(time) as time_sec \nfrom temperature\nwhere source_id='5' and $__timeFilter(time)\norder by time asc "
    }
   ]
  },
  {
   "title": "humidity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "rawSql": "select value, 'stan' as metric, \nUNIX_TIMESTAMP(time) as time_sec \nfrom humidity\nwhere source_id='4' and $__timeFilter(time)\norder by time asc "
    },
    {
     "rawSql": "select value, 'zgb' as metric, \nUNIX_TIMESTAMP(time) as time_sec \nfrom humidity\nwhere source_id='6' and $__timeFilter(time)\norder by time asc "
    }
   ]
  },
  {
   "title": "wind",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select value, 'wind-zg' as metric, \nUNIX_TIMESTAMP(time) as time_sec \nfrom windspeed\nwhere source_id='8' and $__timeFilter(time)\norder by time asc \n"
    }
   ]
  }
 ]
}